#!/usr/bin/env node
/**
 * Self-hosted fonts — run by the owner, not by CI:
 *   npm run fonts            downloads what is missing into public/fonts and rewrites src/styles/fonts.css
 *   npm run fonts -- --force redownloads everything
 *
 * Asks Google Fonts for the variable woff2 of each family (latin + latin-ext,
 * which covers Turkish) and writes @font-face rules that point at ./fonts/…,
 * so the deployed site makes no request to a third party.
 */
import { existsSync, mkdirSync, writeFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const DIR = ROOT + 'public/fonts/';
const CSS = ROOT + 'src/styles/fonts.css';
const force = process.argv.includes('--force');
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36';
const FAMILIES = [
  { key: 'geist', query: 'family=Geist:wght@100..900' },
  { key: 'geist-mono', query: 'family=Geist+Mono:wght@100..900' },
  { key: 'inter-tight', query: 'family=Inter+Tight:wght@100..900' },
  { key: 'instrument-serif-italic', query: 'family=Instrument+Serif:ital@1' },
];
const SUBSETS = ['latin', 'latin-ext'];

mkdirSync(DIR, { recursive: true });
const rules = [];
for (const fam of FAMILIES) {
  const css = await (await fetch(`https://fonts.googleapis.com/css2?${fam.query}&display=swap`, { headers: { 'user-agent': UA } })).text();
  const blocks = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*@font-face\s*{([^}]*)}/g)];
  for (const [, subset, body] of blocks) {
    if (!SUBSETS.includes(subset)) continue;
    const get = prop => (body.match(new RegExp(prop + ':\\s*([^;]+);')) || [])[1]?.trim();
    const url = (body.match(/url\(([^)]+)\)/) || [])[1];
    const file = `${fam.key}-${subset}.woff2`;
    if (force || !existsSync(DIR + file)) {
      const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
      writeFileSync(DIR + file, buf);
    }
    rules.push(`/* ${get('font-family')} — ${subset} */\n@font-face {\n  font-family: ${get('font-family')};\n  font-style: ${get('font-style')};\n  font-weight: ${get('font-weight')};\n  font-display: swap;\n  src: url(/fonts/${file}) format('woff2');\n  unicode-range: ${get('unicode-range')};\n}`);
    console.log(`  ${file.padEnd(36)} ${(statSync(DIR + file).size / 1024).toFixed(0)} KB`);
  }
}
writeFileSync(CSS, `/* Generated by scripts/fonts.mjs — do not edit by hand.  Files live in public/fonts. */\n${rules.join('\n')}\n`);
console.log(`fonts: ${rules.length} faces written to src/styles/fonts.css`);
