#!/usr/bin/env node
/**
 * Renders the knowledge base the Worker answers from — ask/knowledge.txt:
 *   1. ask/knowledge/profile.md, generated here from the English content
 *      (placeholders skipped, [[tokens]] flattened; nothing the site does not show);
 *   2. every other ask/knowledge/*.md the owner drops in (CV, write-ups, code
 *      notes), each with front matter: id (the citation key), title (the chip
 *      label) and an optional href (where a reader can check it: #section,
 *      #projects/<slug> or a URL);
 *   3. the site map the model's [[go|project|cmd:…]] tokens are checked against.
 * Run after every content or knowledge change, then `wrangler deploy`:
 *   node ask/build-prompt.mjs        (or: npm run ask:prompt)
 * It refuses a placeholder and anything shaped like a phone number.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const DIR = ROOT + 'ask/knowledge/';
const { CONTENT } = await import(ROOT + 'src/content/content.ts');
const { LINKS } = await import(ROOT + 'src/content/links.ts');
const { SECTIONS } = await import(ROOT + 'src/content/sections.ts');

const en = v => (v && typeof v === 'object' && 'en' in v ? v.en : v);
const real = s => typeof s === 'string' && s.trim() && !s.startsWith('Placeholder');
const flat = s => String(s).replace(/\[\[([a-z0-9-]+)(?:\|([^\]]+))?\]\]/gi, (_, k, t) => t || LINKS[k]?.label || k);
const para = arr => (Array.isArray(arr) ? arr : []).map(en).filter(real).map(flat);
const c = CONTENT, m = c.meta;

/* ---- 1. the profile, from content.ts ------------------------------------- */
const out = [];
out.push(`# ${m.name}`, `Role: ${flat(en(m.role))}`, `Email: ${m.email}`, /^https?:/.test(m.github) ? `GitHub: ${m.github}` : '', '');
out.push('## In one line', ...[c.hero.line1, c.hero.line2, c.hero.avail].map(en).filter(real).map(flat), '');
if (real(en(c.now.text))) out.push(`## Now (${en(c.now.date)})`, flat(en(c.now.text)), '');
const about = para(c.about); if (about.length) out.push('## About', ...about, '');
const rows = (title, list) => { const r = list.map(e => { const org = flat(en(e.org)); const b = para(e.bullets?.en ? e.bullets.en : []); return `- ${en(e.dates)} — ${flat(en(e.title))}, ${org}${b.length ? '\n  ' + b.join('\n  ') : ''}`; }); if (r.length) out.push(title, ...r, ''); };
rows('## Experience', c.experience); rows('## Education', c.education);
const projects = c.projects.map(p => { const parts = [`- ${flat(en(p.name))} [${p.tags.join(', ')}]${p.stack.length ? ' — ' + p.stack.join(', ') : ''} (slug: ${p.slug})`]; for (const f of [p.problem, p.outcome]) if (real(en(f))) parts.push('  ' + flat(en(f))); const w = para(p.writeup?.en); if (w.length) parts.push('  ' + w.join(' ')); return parts.join('\n'); });
if (projects.length) out.push('## Projects', ...projects, '');
const skills = c.skills.map(g => `- ${en(g.group)}: ${g.items.map(i => en(i.label)).join(', ')}`); if (skills.length) out.push('## Skills', ...skills, '');
const reading = c.reading.filter(r => real(en(r.title))).map(r => `- ${r.date} ${r.kind}: ${flat(en(r.title))} — ${r.authors}${real(en(r.note)) ? '. ' + flat(en(r.note)) : ''}`); if (reading.length) out.push('## Reading', ...reading, '');
const writing = c.writing.filter(w => real(en(w.title))).map(w => `- ${w.date}: ${flat(en(w.title))}`); if (writing.length) out.push('## Writing', ...writing, '');
if (real(en(c.contact.note))) out.push('## Contact preference', flat(en(c.contact.note)), '');
out.push(`(Rendered from the site content, last updated ${m.updated}.)`);
const profile = out.filter(l => l !== undefined && l !== null).join('\n').replace(/\n{3,}/g, '\n\n');
mkdirSync(DIR, { recursive: true });
writeFileSync(DIR + 'profile.md', `---\nid: profile\ntitle: site profile\nhref: '#about'\n---\n<!-- generated by ask/build-prompt.mjs from src/content/content.ts — do not edit; add your own files next to it -->\n${profile}\n`);

/* ---- 2. every knowledge file --------------------------------------------- */
const PHONE = /(?:\+|\b)\d[\d\s().\/-]{7,}\d/g;
const files = [];
for (const name of readdirSync(DIR).filter(f => f.endsWith('.md')).sort((a, b) => (a === 'profile.md' ? -1 : b === 'profile.md' ? 1 : a.localeCompare(b)))) {
  const raw = readFileSync(DIR + name, 'utf8');
  const fm = /^---\n([\s\S]*?)\n---\n/.exec(raw);
  const meta = {}; for (const l of (fm ? fm[1] : '').split('\n')) { const i = l.indexOf(':'); if (i > 0) meta[l.slice(0, i).trim()] = l.slice(i + 1).trim().replace(/^['"]|['"]$/g, ''); }
  const body = (fm ? raw.slice(fm[0].length) : raw).replace(/<!--[\s\S]*?-->\n?/g, '').trim();
  const id = meta.id || name.replace(/\.md$/, '');
  if (!/^[a-z0-9-]+$/.test(id)) fail(`${name}: id "${id}" must be lowercase ASCII (a-z, 0-9, -)`);
  if (files.some(f => f.id === id)) fail(`${name}: id "${id}" is already used`);
  body.split('\n').forEach((l, i) => {
    if (/Placeholder:/.test(l)) fail(`${name}:${i + 1}: a placeholder slipped through`);
    for (const p of l.match(PHONE) || []) if (p.replace(/\D/g, '').length >= 9) fail(`${name}:${i + 1}: "${p}" looks like a phone number — remove it before it leaves the laptop`);
  });
  files.push({ id, title: meta.title || id, href: meta.href || '', body });
}

/* ---- 3. knowledge.txt ---------------------------------------------------- */
const head = [
  '# Knowledge base for Ali Emre Özcan (rendered by ask/build-prompt.mjs; every file below is citable as [src:<id>])',
  '',
  '## Site map (for [[go:…]] [[project:…]] [[cmd:…]] tokens)',
  `Sections: ${SECTIONS.filter(s => s !== 'top').join(', ')}`,
  `Project slugs: ${c.projects.map(p => p.slug).join(', ')}`,
  'Commands: any section name, project <slug>, projects <tag>, contact email, contact github, search <text>',
  '',
];
const text = [...head, ...files.map(f => `=== ${f.id} | ${f.title} | ${f.href}\n${f.body}\n`)].join('\n');
writeFileSync(ROOT + 'ask/knowledge.txt', text);
console.log(`ask/knowledge.txt written — ${files.length} file${files.length === 1 ? '' : 's'} (${files.map(f => f.id).join(', ')}), ${text.length} characters`);

function fail(msg) { console.error('build-prompt: ' + msg); process.exit(1); }
